#cloud-config

# Debian 12 system update
package_update: true
package_upgrade: true

# Installation of required dependencies
packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg
  - lsb-release
  - sudo

# Creation of the user defined
users:
  - name: USER
    groups: sudo
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    ssh-authorized-keys:
      - "SSH KEY"

# SSH configuration and Docker/NodeODM installation
runcmd:
  # Change SSH port and disable root login
  - sed -i 's/#Port 22/Port PORT/' /etc/ssh/sshd_config
  - sed -i 's/#PermitRootLogin yes/PermitRootLogin no/' /etc/ssh/sshd_config
  - sed -i 's/#PasswordAuthentication yes/PasswordAuthentication no/' /etc/ssh/sshd_config
  - systemctl restart sshd
  # Create a swap file with the size defined (32G)
  - fallocate -l 32G /swapfile
  - chmod 600 /swapfile
  - mkswap /swapfile
  - swapon /swapfile
  # Make swap persistent after reboot
  - echo '/swapfile none swap sw 0 0' >> /etc/fstab
  # Add Docker's official GPG key
  - install -m 0755 -d /etc/apt/keyrings
  - curl -fsSL https://download.docker.com/linux/debian/gpg -o /etc/apt/keyrings/docker.asc
  - chmod a+r /etc/apt/keyrings/docker.asc
  # Add Docker repository
  - echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
  # Update packages and install Docker
  - apt-get update
  - apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
  # Add the user defined to the docker group
  - usermod -aG docker USER
  # Start and enable Docker service
  - systemctl enable docker
  - systemctl start docker
  # Launch NodeODM container on port 3001 with the token defined
  - docker run -d --restart unless-stopped -p 3001:3000 opendronemap/nodeodm -q 1 --token TOKEN
  - reboot
